In [1]:
import tensorflow as tf

In [2]:
print("tensorflow gpu:", tf.config.list_physical_devices('GPU'))

tensorflow gpu: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [4]:
tf.constant(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [5]:
tf.constant(2.2, dtype=tf.int32)

TypeError: Cannot convert 2.2 to EagerTensor of dtype int32

In [6]:
tf.constant(2., dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [7]:
tf.constant([True, False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [8]:
tf.constant("hello, world.")

<tf.Tensor: shape=(), dtype=string, numpy=b'hello, world.'>

In [9]:
with tf.device('cpu'):
    a = tf.constant([1])

In [10]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [11]:
with tf.device('gpu'):
    b = tf.constant([1])

In [12]:
a.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [13]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [14]:
tf.device('gpu')

In [15]:
with tf.device('gpu'):
    b = tf.range(4)

In [16]:
b.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [17]:
aa = a.gpu()
aa.device

Instructions for updating:
Use tf.identity instead.


'/job:localhost/replica:0/task:0/device:GPU:0'

In [18]:
b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 1, 2, 3], dtype=int32)>

In [19]:
b.numpy()

array([0, 1, 2, 3], dtype=int32)

In [20]:
b.ndim

1

In [21]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [22]:
tf.rank(tf.ones([3,4,2]))

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [23]:
import numpy as np
a = tf.constant([1.])
b = tf.constant([True, False])
c = tf.constant('hello,world.')
d = np.arange(4)

In [24]:
isinstance(a, tf.Tensor)

True

In [25]:
tf.is_tensor(b)

True

In [26]:
a.dtype, b.dtype

(tf.float32, tf.bool)

In [27]:
a=np.arange(5)

In [28]:
a.dtype

dtype('int64')

In [29]:
aa = tf.convert_to_tensor(a)

In [31]:
aa = tf.convert_to_tensor(a, dtype=tf.int32)