In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
tf.convert_to_tensor(np.ones([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]])>

In [4]:
tf.convert_to_tensor(np.zeros([2,3]))

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]])>

In [5]:
tf.convert_to_tensor([1, 2])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [6]:
tf.convert_to_tensor([1, 2.])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [7]:
tf.convert_to_tensor([[1], [2.]])

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [8]:
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [9]:
tf.zeros([1])

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>

In [10]:
tf.zeros([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [11]:
tf.zeros([2,3,3])

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [12]:
a = tf.zeros([2,3,3])

In [13]:
tf.zeros_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [14]:
tf.zeros(a.shape)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [15]:
tf.ones(1)

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [16]:
tf.ones([])

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [17]:
tf.ones([2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [18]:
tf.ones([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
tf.ones_like(a)

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [20]:
tf.fill([2,2], 0)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [21]:
tf.fill([2,2], 0.)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [22]:
tf.fill([2,2], 1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]], dtype=int32)>

In [23]:
tf.fill([2,2], 9)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 9],
       [9, 9]], dtype=int32)>

# fill填充

# 随机数

In [24]:
tf.random.normal([2,2], mean=1, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.4610874 , 1.909543  ],
       [2.2894397 , 0.06041497]], dtype=float32)>

In [25]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.1597226 ,  0.02798057],
       [-0.43346265,  0.51591665]], dtype=float32)>

In [26]:
tf.random.truncated_normal([2,2], mean=0, stddev=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.2058176 , 0.46987176],
       [0.06105987, 0.6946778 ]], dtype=float32)>

# Gradient Vanish

## Uniform

In [27]:
tf.random.uniform([2,2], minval=0, maxval=1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.12961304, 0.7579669 ],
       [0.07644868, 0.18743086]], dtype=float32)>

In [28]:
tf.random.uniform([2,2], minval=0, maxval=2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.89741683, 1.9490802 ],
       [1.2098372 , 0.26830673]], dtype=float32)>

## Random Permutation 随机打散

In [29]:
idx = tf.range(10)
idx = tf.random.shuffle(idx)

In [30]:
idx

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([9, 4, 6, 2, 3, 0, 5, 1, 8, 7], dtype=int32)>

In [31]:
a = tf.random.normal([10, 784])
b = tf.random.uniform([10], maxval=10, dtype=tf.int32)

In [33]:
a = tf.gather(a, idx)

In [34]:
b = tf.gather(b, idx)

In [35]:
a

<tf.Tensor: shape=(10, 784), dtype=float32, numpy=
array([[-1.9022199 , -0.72735167,  0.83287805, ...,  0.09110986,
        -1.5431114 ,  0.10173114],
       [-0.08974519, -0.2903132 ,  1.0790882 , ...,  1.5538495 ,
         0.8771663 ,  0.5841044 ],
       [ 0.47698143,  0.39737797, -1.1250486 , ..., -0.19496904,
        -1.0128149 ,  0.70792735],
       ...,
       [ 0.08012645,  0.6472537 , -0.40829396, ...,  1.1604201 ,
         0.2484361 ,  0.06541554],
       [ 0.16880494, -0.842402  ,  0.08727842, ...,  0.59521985,
        -1.004174  ,  0.77554256],
       [-0.5350615 ,  0.01105285, -0.98367393, ..., -1.1041582 ,
        -0.16500996, -0.88367385]], dtype=float32)>

In [36]:
b

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([3, 1, 8, 1, 8, 6, 4, 3, 1, 2], dtype=int32)>

In [37]:
out = tf.random.uniform([4, 10])

In [43]:
y = tf.range(4)

In [44]:
y = tf.one_hot(y, depth=10)

In [45]:
loss = tf.keras.losses.mse(y,out)

In [46]:
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.32429406>

In [53]:
from tensorflow.keras import layers

In [54]:
net = layers.Dense(10)
net.build((4, 8))
net.kernel

<tf.Variable 'kernel:0' shape=(8, 10) dtype=float32, numpy=
array([[ 0.14827341, -0.49899542, -0.2562572 ,  0.2800842 , -0.16105309,
         0.25952864, -0.33453274, -0.41408938,  0.30007648,  0.11189663],
       [ 0.43732095,  0.55987096, -0.25915036,  0.34624422, -0.44373778,
        -0.23049238,  0.56711125,  0.44415367, -0.32848588, -0.1124236 ],
       [-0.45694318,  0.33428812, -0.31186038, -0.5352266 ,  0.01589292,
        -0.11297321, -0.3849433 , -0.4154553 , -0.22274593, -0.56544083],
       [-0.18572041, -0.25045976,  0.25666904,  0.11390483, -0.12973306,
         0.42883098, -0.47723886,  0.56163275, -0.48720935, -0.44238177],
       [-0.5415361 , -0.53914   , -0.3394034 , -0.33448884,  0.31240356,
        -0.21752152,  0.30937594, -0.43858275,  0.2952813 ,  0.32896006],
       [ 0.18277389,  0.06989533, -0.3888361 ,  0.52188134,  0.2963255 ,
        -0.18548682, -0.4184557 ,  0.5607252 ,  0.5751381 ,  0.08563352],
       [ 0.56580555,  0.1997742 , -0.01021051,  0.37983578

In [55]:
net.bias

<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>

In [56]:
x = tf.random.normal([4, 784])

In [57]:
net = layers.Dense(10)

In [58]:
net(x).shape

TensorShape([4, 10])

In [59]:
net.kernel.shape

TensorShape([784, 10])

In [60]:
net.bias.shape

TensorShape([10])

In [61]:
a = tf.ones([1, 5, 5, 3])
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [62]:
a[0][0][0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 1.], dtype=float32)>

In [66]:
a[0,3] # numpy的风格

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>