# 聚合操作

In [1]:
import numpy as np

In [5]:
L = np.random.random(100)

In [6]:
L

array([0.80823045, 0.71997879, 0.21104687, 0.70136277, 0.35373072,
       0.10160015, 0.21108231, 0.49895748, 0.95861714, 0.78590316,
       0.11497369, 0.32176642, 0.81692737, 0.78620776, 0.26573479,
       0.51050841, 0.27726982, 0.68033279, 0.289903  , 0.19819274,
       0.76666551, 0.34496856, 0.05639086, 0.35143665, 0.99275465,
       0.09361003, 0.68847145, 0.39553023, 0.81349041, 0.57612848,
       0.735867  , 0.44625519, 0.78621332, 0.72914607, 0.00789355,
       0.13872014, 0.22870212, 0.02880476, 0.98542632, 0.04644265,
       0.51548499, 0.40135885, 0.22601507, 0.67116014, 0.69476113,
       0.90818038, 0.33735401, 0.49478819, 0.16667819, 0.05439725,
       0.31900211, 0.56739409, 0.87142761, 0.60069183, 0.86053763,
       0.62465243, 0.96932998, 0.23433952, 0.77336924, 0.42106964,
       0.33348727, 0.85453555, 0.47759972, 0.87200852, 0.25133456,
       0.48056006, 0.32230663, 0.92629318, 0.93888827, 0.74179856,
       0.98148236, 0.03288921, 0.26903181, 0.18664737, 0.20151

In [7]:
sum(L)

48.333378620541275

In [8]:
np.sum(L)

48.33337862054128

In [9]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

152 ms ± 3.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
408 µs ± 3.71 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [10]:
np.min(big_array)

8.362521919380583e-08

In [11]:
np.max(big_array)

0.9999992936059429

In [12]:
big_array.min()

8.362521919380583e-08

In [13]:
big_array.max()

0.9999992936059429

In [14]:
big_array.sum()

499826.85284838296

In [15]:
X = np.arange(16).reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.sum(X)

120

In [17]:
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [18]:
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [19]:
np.prod(X)

0

In [21]:
np.prod(X + 1)

20922789888000

In [23]:
np.mean(X)

7.5

In [24]:
np.median(X)

7.5

In [25]:
v = np.array([1,1,2,2,10])

In [26]:
np.mean(v)

3.2

In [27]:
np.median(v)

2.0

In [29]:
np.percentile(big_array, q=50)

0.4999431902799597

In [30]:
np.percentile(big_array, q = 100)

0.9999992936059429

In [31]:
np.max(big_array)

0.9999992936059429

In [32]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q=percent))

8.362521919380583e-08
0.24972989159892592
0.4999431902799597
0.7496088722359041
0.9999992936059429


In [33]:
np.var(big_array)

0.08330563631638255

In [34]:
np.std(big_array)

0.28862715796747634

In [35]:
x = np.random.normal(0, 1, size=1000000)

In [36]:
x

array([ 0.98188648, -0.26672927,  1.00666248, ..., -0.7878679 ,
        0.63440769, -1.75158139])

In [37]:
np.mean(x)

-0.00023512516809286678

In [38]:
np.std(x)

1.0007392847775147

# 索引

In [39]:
np.min(x)

-4.952851780465117

In [40]:
np.argmin(x)

509248

In [41]:
np.argmax(x)

231005

## 排序和使用索引

In [42]:
x = np.arange(16)

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
np.random.shuffle(x)

In [45]:
x

array([ 7,  5, 13, 10, 11,  0,  9,  2, 15, 12,  6,  3,  8, 14,  1,  4])

In [46]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [47]:
x

array([ 7,  5, 13, 10, 11,  0,  9,  2, 15, 12,  6,  3,  8, 14,  1,  4])

In [49]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
X = np.random.randint(10, size=(4,4))

In [51]:
X

array([[5, 9, 3, 3],
       [9, 4, 4, 2],
       [4, 9, 4, 5],
       [3, 3, 9, 1]])

In [53]:
np.sort(X, axis=0)

array([[3, 3, 3, 1],
       [4, 4, 4, 2],
       [5, 9, 4, 3],
       [9, 9, 9, 5]])

In [54]:
np.random.shuffle(x)

In [55]:
x

array([10, 14,  6,  2, 15,  5, 13,  7, 11,  1,  4,  8, 12,  9,  0,  3])

In [56]:
np.argsort(x)

array([14,  9,  3, 15, 10,  5,  2,  7, 11, 13,  0,  8, 12,  6,  1,  4])

In [57]:
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7, 11, 14, 13,  8, 12,  9, 15, 10])

In [58]:
np.argpartition(x, 3)

array([14,  9,  3, 15, 10,  5,  2,  7,  8,  1,  6, 11, 12, 13,  4,  0])

In [59]:
X

array([[5, 9, 3, 3],
       [9, 4, 4, 2],
       [4, 9, 4, 5],
       [3, 3, 9, 1]])

In [60]:
np.argsort(X, axis=1)

array([[2, 3, 0, 1],
       [3, 1, 2, 0],
       [0, 2, 3, 1],
       [3, 0, 1, 2]])