In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

## train_test_split

In [6]:
X[:120]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
shuffle_indexes = np.random.permutation(len(X))

In [10]:
shuffle_indexes

array([ 89, 148,  18,  36,   4,  23, 100, 103, 127,   3, 106, 101,  34,
        82,  91,  21,   6,  37,  76, 142,   0,  70, 111, 147, 125,  30,
        83,  10,   8,  42,  99, 131, 149,  68,  33, 112, 104,  47,  32,
        59,  51,  20,  48,  55,  11,   7,  79,  97,  24, 119, 124,  64,
       115,  19,   2,  53,  39,  52, 134, 137,  22, 126,  92,   9, 121,
        50, 146, 133, 108,  25,  85,  41,  43,  78, 138,  44, 113,  31,
       136,  57, 129,  80,  63, 110,  26,  58,  49,  94,  45, 107, 117,
        96,  60,  15,  14,  72,  90,  71,  74,  65, 140,  95,  27,  98,
        61, 120, 130, 102,  77, 116, 144,  17,  38, 141,   5, 143, 132,
       145, 122,  87,  75, 135,  93,  16,  54,  46,   1,  28,  69, 139,
        88, 118,  13,  67, 109,  29,  40,  56,  73,  35, 123,  81,  62,
       114,  12,  84, 128,  66,  86, 105])

In [11]:
test_ratio = 0.2

In [16]:
test_size = int(len(X) * test_ratio)

In [17]:
test_size

30

In [18]:
test_indexes = shuffle_indexes[:test_size]

In [19]:
train_indexes = shuffle_indexes[test_size:]

In [20]:
X_train = X[train_indexes]
y_train = y[train_indexes]
X_test = X[test_indexes]
y_test = y[test_indexes]

In [21]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


# 使用我们的算法

In [22]:
from test_algorithm.playML.model_selection import train_test_split

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [24]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [25]:
from test_algorithm.playML.knn import KNNClassifier

In [26]:
my_knn_clf = KNNClassifier(k=3)

In [27]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [29]:
y_predict = my_knn_clf.predict(X_test)

In [30]:
y_test

array([1, 1, 2, 2, 1, 1, 0, 2, 0, 2, 2, 1, 1, 0, 2, 0, 1, 2, 1, 0, 2, 2,
       1, 2, 2, 1, 0, 1, 1, 1])

In [31]:
sum(y_predict == y_test)

28